[package]
name = "cahwar/tak-home-assignment"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.3.1"
component = "sleitnick/component@2.4.8"
timer = "sleitnick/timer@2.0.0"